#!/usr/bin/env python3
"""Convert Meta's jollybot.gif into LVGL RGB565 frame arrays for the grinder.

Reads the GIF from $JOLLY_GIF, or <repo>/../muse-gadget-sdk/esp32/avatar/jollybot.gif,
or ~/workspace/coffee-gadgets/muse-gadget-sdk/esp32/avatar/jollybot.gif.

Writes src/muse/jolly_anim.c + jolly_anim.h (both gitignored).

No Meta art is committed to the repo: the Jolly artwork is Meta-copyrighted
(see the gadget SDK's esp32/AGENTS.md — the Apache license does not cover it).
Only this script (which contains no art) is committed; the generated frames
stay on the builder's machine for personal use.

Usage: python3 tools/gen_jolly.py [--gif PATH] [--out-dir src/muse]
"""

import argparse
import os
import pathlib
import sys

FRAME_W = 112
FRAME_H = 112
FRAME_STEP = 3          # every 3rd GIF frame (40ms -> 120ms per frame)
BLACK_THRESHOLD = 16    # pixels darker than this count as background

REPO = pathlib.Path(__file__).resolve().parent.parent
DEFAULT_CANDIDATES = [
    pathlib.Path(os.environ["JOLLY_GIF"]) if os.environ.get("JOLLY_GIF") else None,
    REPO.parent / "muse-gadget-sdk" / "esp32" / "avatar" / "jollybot.gif",
    pathlib.Path.home() / "workspace" / "coffee-gadgets" / "muse-gadget-sdk"
    / "esp32" / "avatar" / "jollybot.gif",
]


def find_gif(explicit):
    if explicit:
        p = pathlib.Path(explicit)
        if p.is_file():
            return p
        sys.exit(f"gen_jolly: GIF not found at {p}")
    for c in DEFAULT_CANDIDATES:
        if c and c.is_file():
            return c
    sys.exit(
        "gen_jolly: jollybot.gif not found.\n"
        "  Set $JOLLY_GIF to esp32/avatar/jollybot.gif in your local\n"
        "  muse-gadget-sdk clone, or place the clone next to this repo as\n"
        "  ../muse-gadget-sdk."
    )


def rgb565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def main():
    from PIL import Image

    ap = argparse.ArgumentParser()
    ap.add_argument("--gif", default=None)
    ap.add_argument("--out-dir", default=str(REPO / "src" / "muse"))
    args = ap.parse_args()

    gif_path = find_gif(args.gif)
    out_dir = pathlib.Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    print(f"gen_jolly: reading {gif_path}")

    gif = Image.open(gif_path)
    n = gif.n_frames
    idxs = list(range(0, n, FRAME_STEP))
    frames = []
    for i in idxs:
        gif.seek(i)
        frames.append(gif.convert("RGB"))

    # Union bbox of non-black pixels across sampled frames.
    x0, y0, x1, y1 = gif.width, gif.height, 0, 0
    for fr in frames:
        px = fr.load()
        for y in range(0, gif.height, 2):
            for x in range(0, gif.width, 2):
                r, g, b = px[x, y]
                if r > BLACK_THRESHOLD or g > BLACK_THRESHOLD or b > BLACK_THRESHOLD:
                    if x < x0: x0 = x
                    if y < y0: y0 = y
                    if x > x1: x1 = x
                    if y > y1: y1 = y
    pad = 6
    x0, y0 = max(0, x0 - pad), max(0, y0 - pad)
    x1, y1 = min(gif.width, x1 + pad), min(gif.height, y1 + pad)

    converted = []
    for fr in frames:
        small = fr.crop((x0, y0, x1, y1)).resize((FRAME_W, FRAME_H), Image.LANCZOS)
        px = small.load()
        buf = bytearray()
        for y in range(FRAME_H):
            for x in range(FRAME_W):
                v = rgb565(*px[x, y])
                buf.append(v & 0xFF)
                buf.append(v >> 8)
        converted.append(bytes(buf))

    count = len(converted)
    print(f"gen_jolly: {count} frames, {FRAME_W}x{FRAME_H} RGB565 "
          f"({len(converted[0]) * count // 1024} KiB flash)")

    # ---- jolly_anim.h ----
    h = f"""// Generated by tools/gen_jolly.py from jollybot.gif — DO NOT EDIT, DO NOT COMMIT.
// Meta-copyrighted artwork; generated at build time for personal use only.
#pragma once
#include <lvgl.h>
#include <stdint.h>

#define JOLLY_FRAME_W {FRAME_W}
#define JOLLY_FRAME_H {FRAME_H}
#define JOLLY_FRAME_COUNT {count}
#define JOLLY_FRAME_MS {40 * FRAME_STEP}

#ifdef __cplusplus
extern "C" {{
#endif

const lv_image_dsc_t* jolly_get_frame(int i);

#ifdef __cplusplus
}}
#endif
"""
    (out_dir / "jolly_anim.h").write_text(h)

    # ---- jolly_anim.c ----
    parts = [
        "// Generated by tools/gen_jolly.py from jollybot.gif — DO NOT EDIT, DO NOT COMMIT.",
        "// Meta-copyrighted artwork; generated at build time for personal use only.",
        '#include "jolly_anim.h"',
        "",
    ]
    for i, buf in enumerate(converted):
        hexbytes = ", ".join(f"0x{b:02x}" for b in buf)
        parts.append(f"static const uint8_t jolly_frame_{i}[{len(buf)}] = {{{hexbytes}}};")
    parts.append("")
    parts.append(f"static const lv_image_dsc_t jolly_frames[JOLLY_FRAME_COUNT] = {{")
    for i in range(count):
        parts.append(
            f"    {{ .header = {{ .cf = LV_COLOR_FORMAT_RGB565, .w = JOLLY_FRAME_W,"
            f" .h = JOLLY_FRAME_H, .stride = JOLLY_FRAME_W * 2, .flags = 0 }},"
            f" .data_size = sizeof(jolly_frame_{i}), .data = jolly_frame_{i} }},"
        )
    parts.append("};")
    parts.append("")
    parts.append("const lv_image_dsc_t* jolly_get_frame(int i) {")
    parts.append("    if (i < 0) i = 0;")
    parts.append("    return &jolly_frames[i % JOLLY_FRAME_COUNT];")
    parts.append("}")
    parts.append("")
    (out_dir / "jolly_anim.c").write_text("\n".join(parts))
    print(f"gen_jolly: wrote {out_dir / 'jolly_anim.c'} and jolly_anim.h")


if __name__ == "__main__":
    main()
